// API Message Constants
const SPLASH = "SPLASH";
const LOGIN = "LOGIN";
const PAGES = "DASHBOARD";
const REFDATA = "REF_DATA";
const GETASSIGNTASK = "GET_ASSIGNED_UN_ASSIGNED_TASK";
const ASSIGNEDTASK = "ASSIGNED_TASK";
const FILTERLIST = "FILTER_LIST";
const VIEW = "VIEW";
const UPDATE = "UPDATE";
const DELETE = "DELETE";
const ADD = "ADD";
const RESETPASSWORD = "RESET_PASSWORD";
const EXUPLOAD = "EX_UPLOAD";
const LOGOUT = "LOGOUT";
const SAMPLEDOWNLOAD = "SAMPLE_FORMAT_DOWNLOAD";
const REQUESTOTP = "RESET_PASSWORD_OTP_REQUEST";
const VALIDATEOTP = "RESET_PASSWORD_OTP_VALIDATION";
const DEATHCLAIMREQUEST = "DEATH_CLAIM_REQUEST";

export {
  LOGIN,
  PAGES,
  REFDATA,
  GETASSIGNTASK,
  ASSIGNEDTASK,
  FILTERLIST,
  VIEW,
  UPDATE,
  DELETE,
  ADD,
  RESETPASSWORD,
  EXUPLOAD,
  LOGOUT,
  SAMPLEDOWNLOAD,
  REQUESTOTP,
  VALIDATEOTP,
  DEATHCLAIMREQUEST,
  SPLASH,
};
